### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [viktak/ActoSenso-Node-wifi-ir-gateway#1]
Hello!

I found link to this project from https://hackaday.com/2020/10/14/an-open-source-ir-gateway-based-on-the-esp8266/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by viktak** [comment]
Hi there!
My code uses several other pieces of code (libraries) from other authors with varying licenses. I am not a legal expert, so I cannot assert what licensing form is permitted/suitable for my resulting work. I would love to use a license with very little restriction, but I cannot give you a license to use someone else's work.

I open sourced my code so that people can audit it, learn from it, etc.

If/when I will have the time I to do some research on this subject and I will include a license if it makes sense.

**Comment by vazhnov** [comment]
@viktak , then I suggest to start collecting information about third-party code here in this chat. After some time, maybe we will have full picture.

For example:

* `src/NTP.h` — Craig A. Lindley, license = unknown
* `src/main.cpp` — Viktor, license = ?

**Comment by viktak** [comment]
Licensing info added

**Comment by vazhnov** [comment]
Hmmm, CC BY-NC-SA 4.0 — strange but better than nothing. I don't like "NC" licenses :)
Thank you!
